### ISSUE TITLE
Метод player.sumGenre не обновляет суммарное время игры по одному жанру

### ISSUE THREAD

**Issue by Topcer** [aaskripkina/javaqa-team-diplom#5]
# Описание
Метод player.SumGenre в классе Player не суммирует проигранное время игры одного жанра этим игроком

# Локация дефекта
https://github.com/aaskripkina/javaqa-team-diplom/blob/c3973225b06cfdca16ab1f45f75d21a497dae27d/src/main/java/ru/netology/Player.java#L43-L55 
# Шаги воспроизведения
1. Открыть [Test-class  класса Player](https://github.com/aaskripkina/javaqa-team-diplom/blob/c3973225b06cfdca16ab1f45f75d21a497dae27d/src/test/java/ru/netology/PlayerTest.java) в IDEA;
2. Запустить [тест shouldSumGenreIfOneGame](https://github.com/aaskripkina/javaqa-team-diplom/blob/c3973225b06cfdca16ab1f45f75d21a497dae27d/src/test/java/ru/netology/PlayerTest.java#L9);
3. Посмотреть на результат теста в консоли.

# Логика теста shouldSumGenreIfOneGame:

1. Создать объект класса GameStore;
2. Создать элемент коллекции Game game через присвоение результата работы метода publishGame: store.publishGame("Нетология Баттл Онлайн", "Аркады");
3. Создать объект игрока Player;
4. Установить игру с помощью метода player.installGame(game);
5. Поиграть в игру в течении 3 часов с помощью метода player.play(game, 3);
6. Сравнить через assertEquals результат вызова метода sumGenre(game) с значением 3 часов игры.

*Ожидаемый результат:* Результат теста - Время игрока равно установленному - 3 часам, метод sumGenre вернул значение 3. 
*Фактический результат:* Результат теста - Время игрока равно 0 часов, метод sumGenre вернул значение 0.
# Скриншот
![sumGenry](https://user-images.githubusercontent.com/22979834/226420252-0b039440-25c5-4f33-b1b5-30e8f7b4e421.jpg)

# Окружение
* **Операционная система:** Windows 10 Pro
* **IDE:** IntelliJ IDEA 2022.3.1 (Community Edition)
* **Java:** OpenJDK 11

**Comment by aaskripkina** [comment]
Исправлено 
![Ишью 1](https://user-images.githubusercontent.com/120738830/226423540-c5be67bc-6557-4185-921b-3e4814211e6d.jpg)
