### ISSUE TITLE
Метод player.play возвращает количество сыгранных часов игры, без установки самой игры.

### ISSUE THREAD

**Issue by Topcer** [aaskripkina/javaqa-team-diplom#6]
# Описание
Метод player.play в классе Player возвращает количество времени, сыгранное игроком, без предварительной установки игры методом player.installGame(game);

# Локация дефекта
https://github.com/aaskripkina/javaqa-team-diplom/blob/c3973225b06cfdca16ab1f45f75d21a497dae27d/src/main/java/ru/netology/Player.java#L33-L41
 
# Шаги воспроизведения
1. Открыть [Тест-класс  класса Player](https://github.com/manny1892/TeamProject/blob/player/src/test/java/ru/netology/PlayerTest.java) в IDEA;
2. Запустить тест `shouldCheckOnPlayWithoutInstall`;
3. Посмотреть на результат теста в консоли.

*Ожидаемый результат:* Результат теста - Исключение RuntimeExceptions сработало, не возможно получить значение метода.
*Фактический результат:* Результат теста - Ошибка, RuntimeException не был найден.

# Скриншот 
![1679337516760](https://user-images.githubusercontent.com/22979834/226435557-98e62d03-29a5-4063-bfc2-210cdd870020.jpg)

# Окружение
* **Операционная система:** Windows 10 Pro
* **IDE:** IntelliJ IDEA 2022.3.1 (Community Edition)
* **Java:** OpenJDK 11

**Comment by aaskripkina** [comment]
Исправлено
![Ишью 2](https://user-images.githubusercontent.com/120738830/226445632-192e7909-198f-4576-b6fd-32683036c4cc.jpg)
