### ISSUE TITLE
Метод player.play() не суммирует значение сыгранных часов после метода player.installGame()

### ISSUE THREAD

**Issue by Topcer** [aaskripkina/javaqa-team-diplom#7]
# Описание
Метод player.play() в классе Player не суммирует значение - количество времени, сыгранное игроком, после установки игры методом player.installGame();

# Локация дефекта
https://github.com/aaskripkina/javaqa-team-diplom/blob/c3973225b06cfdca16ab1f45f75d21a497dae27d/src/main/java/ru/netology/Player.java#L33-L41
 
# Шаги воспроизведения
1. Открыть [Тест-класс  класса Player](https://github.com/manny1892/TeamProject/blob/player/src/test/java/ru/netology/PlayerTest.java) в IDEA;
2. Запустить тест `shouldCheckPlayToSumHoursSameGenreGames`;
3. Посмотреть на результат теста в консоли.

# Логика теста shouldCheckPlayToSumHoursSameGenreGames:

1. Создать объект класса GameStore;
2. Создать элемент коллекции Game game через присвоение результата работы метода publishGame: store.publishGame("Нетология Баттл Онлайн", "Аркады");
3. Создать объект игрока Player;
4. Применить метод установки игры - player.installGame(game);
5. Поиграть в игру в течении 2 часа с помощью метода player.play(game, 2)
6. Повторно поиграть в эту игру еще раз в течении 7 часов с помощью метода player.play(game, 7)
7. Сравнить через assertEquals результат вызова метода sumGenre(game) с общим количеством часов равное 9.

*Ожидаемый результат:* Результат теста - Время игрока равно 9 часам, метод sumGenre вернул суммарное значение равное 9.
*Фактический результат:* Результат теста - Игровое время установлено в значение 0.
 
# Скриншот
![1679339066670](https://user-images.githubusercontent.com/22979834/226441435-d5922746-f699-479b-8946-6aee16262ed0.jpg)

# Окружение
* **Операционная система:** Windows 10 Pro
* **IDE:** IntelliJ IDEA 2022.3.1 (Community Edition)
* **Java:** OpenJDK 11

**Comment by aaskripkina** [comment]
Исправлено
![Ишью3](https://user-images.githubusercontent.com/120738830/226447358-a48a7c10-ba0e-4900-8c6f-4a5b46460222.jpg)
