### ISSUE TITLE
Метод player.installGame(game) обнуляет время игры при повторной установке

### ISSUE THREAD

**Issue by Topcer** [aaskripkina/javaqa-team-diplom#8]
# Описание
Метод player.installGame(game) в классе Player обнуляет время игры, при повторной установки игры player.installGame(game), после метода player.play(game).

# Локация дефекта
https://github.com/aaskripkina/javaqa-team-diplom/blob/c3973225b06cfdca16ab1f45f75d21a497dae27d/src/main/java/ru/netology/Player.java#L24-L25

# Шаги воспроизведения
1. Открыть [Тест-класс  класса Player](https://github.com/manny1892/TeamProject/blob/player/src/test/java/ru/netology/PlayerTest.java) в IDEA;
2. Запустить тест `shouldInstallGame`;
3. Посмотреть на результат теста в консоли.

# Логика теста shouldInstallGamee:

1. Создать объект класса GameStore;
2. Создать элемент коллекции Game game через присвоение результата работы метода publishGame: store.publishGame("Нетология Баттл Онлайн", "Аркады");
3. Создать объект игрока Player;
4. Применить метод установки игры - player.installGame(game);
5. Поиграть в игру в течении 2 часов с помощью метода player.play(game, 2);
6. Повторно применить метод установки игры - player.installGame(game);
7. Сравнить через assertEquals результат вызова метода sumGenre("Аркады") с общим количеством часов игры равное 2.

*Ожидаемый результат:* Результат теста - Время игрока равно 2 часам, метод sumGenre вернул суммарное значение равное 2.
*Фактический результат:* Результат теста - Игровое время установлено в значение 0.

# Скриншот
![1679340487989](https://user-images.githubusercontent.com/22979834/226445648-63ab597c-475f-4cdd-b300-8ee769ea48e0.jpg)

# Окружение
* **Операционная система:** Windows 10 Pro
* **IDE:** IntelliJ IDEA 2022.3.1 (Community Edition)
* **Java:** OpenJDK 11

**Comment by aaskripkina** [comment]
Исправлено
![Ишью 4](https://user-images.githubusercontent.com/120738830/226448928-83873280-cba0-4677-964b-9cb971418524.jpg)
