### ISSUE TITLE
Метод player.mostPlayerByGenre(genre) не возвращает название жанра игры

### ISSUE THREAD

**Issue by Topcer** [aaskripkina/javaqa-team-diplom#9]
# Описание
Метод player.mostPlayerByGenre(genre) в классе Player не возвращает название игры жанра, в которую играли больше всего, а возвращает значение null.

# Локация дефекта
https://github.com/aaskripkina/javaqa-team-diplom/blob/c3973225b06cfdca16ab1f45f75d21a497dae27d/src/main/java/ru/netology/Player.java#L57-L61

# Шаги воспроизведения
1. Открыть [Тест-класс  класса Player](https://github.com/manny1892/TeamProject/blob/player/src/test/java/ru/netology/PlayerTest.java) в IDEA;
2. Запустить тест `mostPlayerByGenre`;
3. Посмотреть на результат теста в консоли.

# Логика теста mostPlayerByGenre:

1. Создать объект класса GameStore;
2. Создать элемент коллекции Game game через присвоение результата работы метода publishGame: store.publishGame("Нетология Баттл Онлайн", "Аркады");
3. Создать элемент коллекции Game game2 через присвоение результата работы метода publishGame: store.publishGame("TF2", "Шутер");
4. Создать объект игрока Player;
5. Применить метод установки игры - player.installGame(game);
6. Применить метод установки игры - player.installGame(game2);
7. Поиграть в игру в течении 7 часов с помощью метода player.play(game, 7);
8. Поиграть в игру в течении 3 часов с помощью метода player.play(game, 3);
9. Сравнить через assertEquals результат вызова метода player.mostPlayerByGenre("Аркады") с методом получения названия игры жанра game.getTitle().

*Ожидаемый результат:* Результат теста - Метод player.mostPlayerByGenre("Аркады") вернул название игры жанра, в которое играли больше всего - "Нетология Баттл Онлайн".
*Фактический результат:* Результат теста - Получено значение "Null".

# Скриншот 
![1679341329620](https://user-images.githubusercontent.com/22979834/226448586-2d9e3254-56da-4ae0-94ef-f3e8be31f163.jpg)

# Окружение
* **Операционная система:** Windows 10 Pro
* **IDE:** IntelliJ IDEA 2022.3.1 (Community Edition)
* **Java:** OpenJDK 11

**Comment by aaskripkina** [comment]
Исправлено
![Ишью 5](https://user-images.githubusercontent.com/120738830/226461510-942cd5c8-46c4-40ff-99db-02a2013f0159.jpg)
